### ISSUE TITLE
Interface Capacitive Touch Sensor with BeagleBone Black

### ISSUE THREAD

**Issue by MohitRane8** [cu-ecen-5013/final-project-assignment-MohitRane8#10]
**DoD:**
Capacitive touch sensor functionality check on BBB (sensor output correct values). Interface the touch sensor with the BBB using GPIO port pins. The physical touch on the touchpad will output "touch" on the serial terminal whereas, in the case of no physical contact, the terminal message will read "Not touched". Period of measurement will be 500 ms.

**Status:**
DoD verified
Associated commit: https://github.com/cu-ecen-5013/Mohit-Amogh-Final-ProjectSource/commit/6187a118adfa78a13b7478ba8dea826aee6e99ff

**Sensor output:**
![image](https://user-images.githubusercontent.com/45619385/70214555-e18c7300-16f8-11ea-92d4-794bb9d74bb3.png)

**Comment by steveantony5** [comment]
@MohitRane8 What would happen to system if the sensor is non operational?
