### ISSUE TITLE
Documentation for enabling UART on BBB

### ISSUE THREAD

**Issue by MohitRane8** [cu-ecen-5013/final-project-assignment-MohitRane8#17]
**DoD:**
The wiki page should demonstrate all the steps that can be undertaken by a user on his buildroot folder for enabling the UART pins on BBB running Linux built using Buildroot.

**Status:**
Completed

**Comment by steveantony5** [comment]
@MohitRane8  @AmoghShrikhande  Please remove character device and socket implementation from the project overview page as you didn't have time to do it

**Comment by steveantony5** [comment]
@MohitRane8  Please remove the  tasks which were not done from the diagram. I am not sure if the log task was working as it uses char device driver which was not completed

**Comment by MohitRane8** [comment]
DoD verified
