### ISSUE TITLE
Follow-On: Interface Actuators on BeagleBone Black

### ISSUE THREAD

**Issue by AmoghShrikhande** [cu-ecen-5013/final-project-assignment-MohitRane8#19]
**Original Issue:**
Interface Actuators on BeagleBone Black #12

**Original DoD:**
Successfully implement a simple code, that can run PWM functionality on any of the port pin configured as GPIO on BBB.

**Redefined DoD:**
Print PWM values received from TIVA on serial terminal.

**Status:**
Redefined DoD verified

**Comment by steveantony5** [comment]
@AmoghShrikhande Please elaborate DoD as it is not clear. Please mention that you need PWM for brightness control. I guess that is the main work behind this task. 
Elaborate and explain how are you planning to verify this task?

**Comment by MohitRane8** [comment]
Blocker: Unable to activate PWM pins on Beaglebone Black.
