### ISSUE TITLE
Interface Ultrasonic Sensor with BeagleBone Black

### ISSUE THREAD

**Issue by MohitRane8** [cu-ecen-5013/final-project-assignment-MohitRane8#9]
**DoD:**
Ultrasonic sensor functionality check on BBB (sensor output correct values). Bring the Ultrasonic sensor near to an obstacle. Check if the sensor outputs the correct value for the distance between the sensor and the obstacle. Take the ultrasonic sensor away from the obstacle. Check the values outputted by the sensor in this case. Logically verify the results obtained.

**Note:**
This issue is carried forward to the next sprint 

**Status:**
Moved to next sprint

**Follow-on task:**
#20

**Comment by steveantony5** [comment]
@AmoghShrikhande  It explains how to validate an ultrasonic sensor. Please explain with reference to your application. How to validate it from your application perspective? Will any actuator turn off/on based on the ultrasonic sensor reading?

**Comment by AmoghShrikhande** [comment]
Ok. Got it. I will make the necessary changes

**Comment by AmoghShrikhande** [comment]
Yes, I will explain the validation details in the integration task

**Comment by steveantony5** [comment]
@AmoghShrikhande What would be the state of the system when the sensor is non operational?
